directories:
  pdfs: "PDFs" #relative to script directory
  data: "scripts/data" #relative to script directory
  jsons: "scripts/data/jsons" #relative to script directory
  
logger:
  level: "DEBUG"  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(levelname)s - %(message)s"  # Log message format
  datefmt: "%Y-%m-%d %H:%M:%S"  # Date format for log messages
  filename: "pdf_scraper.log"  # Log file name
  max_bytes: 5242880 # 5MB
  backup_count: 5


jurisdiction_scoring:
  field_weights: { # the importance value of if a field is present in the data for a case, 0 means we place no value on this field being present
    case_id: 0.0,
    jurisdiction: 0.0,
    case_type: 2.0,
    incident_date: 1.5,
    incident_location: 1.2,
    mentioned_locations: 0.0,
    injuries_described: 2.0,
    medical_treatment_mentioned: 1.5,
    employment_impact_mentioned: 1.0,
    property_damage_mentioned: 0.8,
    entities_mentioned: 0.2,
    insurance_mentioned: 0.6,
    witnesses_mentioned: 0.5,
    prior_legal_representation_mentioned: 0.2,
    case_outcome: 2.5,
    settlement_value: 3.0,
    communication_channel: 0.0,
    key_phrases: 0.0,
    summary: 0.0,
  }

    
