directories:
  data: "scripts/data" 
  jsons: "scripts/data/jsons"
  logs: "logs"
  chat_logs: "scripts/data/chat_logs"
  feedback: "scripts/data/feedback"

logger:
  level: "DEBUG"  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log message format
  datefmt: "%Y-%m-%d %H:%M:%S"  # Date format for log messages
  filename: "legal_lead.log"  # Log file name
  max_bytes: 2000000 # 2MB
  backup_count: 5

aiconfig:
  default_encoding: "o200k_base"
  vector_search:
    default_chunk_limit: 10  # Default number of chunks returned from vector search

lead_scoring:
  case_enrichment:
    primary_case_data_pdf_location: 'C:\Users\Justin\Desktop\Law_RAG\scripts\data\case_data\webDGCase.xlsx'

jurisdiction_scoring:
  field_weights: { # the importance value of if a field is present in the data for a case, 0 means we place no value on this field being present
    case_id: 0.0,
    jurisdiction: 0.0,
    case_type: 2.0,
    incident_date: 1.5,
    incident_location: 1.2,
    mentioned_locations: 0.0,
    injuries_described: 2.0,
    medical_treatment_mentioned: 1.5,
    employment_impact_mentioned: 1.0,
    property_damage_mentioned: 0.8,
    entities_mentioned: 0.2,
    insurance_mentioned: 0.6,
    witnesses_mentioned: 0.5,
    prior_legal_representation_mentioned: 0.2,
    case_outcome: 3.0,
    settlement_value: 5.0,
    communication_channel: 0.0,
    key_phrases: 0.0,
    summary: 0.0,
  }
  bayesian_shrinkage:
    conservative_factor: 10  # Higher values = more conservative = more shrinkage toward global average

caching:
  directories:
    summary: "scripts/data/caching/summary_cache"